import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react';
import styles from '../styles/Home.module.css'

export default function Home() {
  const [nightmares, updateNightmares] = useState("Empty")

  function getNightmares()
  {
    fetch("http://localhost:3000/api/nightmares")
    .then(response => response.text())
    .then(text => updateNightmares(text));
  }



  return (
    <div className={styles.container}>
      <Head>
        <title>SINoALICE Nightmare Plotter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/alice.ico" />
      </Head>
      <button type="button" onClick={getNightmares}>Fetch Nightmares</button> 
      <p>{nightmares}</p>
    </div>

  )
}
